name: Deploy to Smallhost

on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PHP dependencies
        run: composer install --no-dev --prefer-dist

      - name: Install Node dependencies
        run: yarn install

      - name: Build frontend
        run: yarn build

      - name: Upload frontend (public/build)
        uses: genietim/ftp-action@v4
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          localDir: "public/build"
          remoteDir: "public_html/build"

      - name: Upload backend (Laravel)
        uses: genietim/ftp-action@v4
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          localDir: "."
          remoteDir: "."
          exclude: "public/build"
