name: ðŸš€ Deploy website on push

on:
  push:
    branches: [ "main" ]  

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: Install PHP dependencies
        run: composer install --no-dev --prefer-dist

      - name: Install Node dependencies
        run: yarn install

      - name: Build frontend
        run: yarn build

      - name: Upload frontend via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          security: loose
          local-dir: public/build/
          server-dir: domains/animated-sections---laravel-ts-scss.vkohut1807.smallhost.pl/public_html/build/
          dry-run: false  

      - name: Upload backend via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          security: loose
          local-dir: ./
          server-dir: domains/animated-sections---laravel-ts-scss.vkohut1807.smallhost.pl
          exclude: public/build/
          dry-run: false
