name: Deploy to Smallhost

on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PHP dependencies
        run: composer install --no-dev --prefer-dist

      - name: Install Node dependencies
        run: yarn install

      - name: Build frontend
        run: yarn build

      - name: Upload frontend (public/build)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: 22
          source: "public/build/*"
          target: "public_html/build"

      - name: Upload backend (Laravel)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: 22
          source: "./{app,bootstrap,config,database,routes,resources,storage,vendor,artisan,.env}"
          target: "."
